### ISSUE TITLE
Typescript version does not build

### ISSUE THREAD

**Issue by ghost** [benjammin4dayz/neu-react-vite#6]
After converting to Typescript, the project will not build successfully (neu build) due to multiple Typescript errors in the generated code

**Comment by benjammin4dayz** [comment]
Hey @coderguy-21, thanks for submitting this issue!

I was only able to reproduce one error after a fresh conversion on commit 69134fb. Is this what you were encountering?

```
src/App.tsx:9:19 - error TS7006: Parameter 'err' implicitly has an 'any' type.
9 const logError = (err) => console.log(err);
                    ~~~
Found 1 error in src/App.tsx:9
```

This is resolved in commit 1c54fed: promise returning function calls to Neutralino are now voided instead of using a catch handler to prevent floating promises.
